apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.author }}-service
  labels:
    app:    service
    author: {{ .Values.author }}
spec:
  selector:
    app:    service
    author: {{ .Values.author }}
  ports:
    - name: web
      port: {{ .Values.port }}
      targetPort: {{ .Values.servicePort }}
  type: ClusterIP
